# Generated by Django 3.1.7 on 2021-03-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.FloatField(default=0.0, verbose_name='Стоимость')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('dateOfCreation', models.DateField(blank=True, null=True, verbose_name='Дата Создания')),
                ('numpages', models.IntegerField(default=0, verbose_name='Количество страниц')),
                ('genre', models.CharField(max_length=30, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.FloatField(default=0.0, verbose_name='Стоимость')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('dateOfCreation', models.DateField(blank=True, null=True, verbose_name='Дата Создания')),
                ('type', models.CharField(max_length=20, verbose_name='Тип')),
                ('publisher', models.CharField(max_length=50, verbose_name='Издатель')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
    ]
